# Generated by Django 4.1.7 on 2023-04-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_rename_colour_theme_displaymode_display_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='login_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notes.logindetails'),
        ),
    ]
