# Generated by Django 4.1.7 on 2023-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_logindetails_note_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='password',
            field=models.CharField(default='rosa_parks', max_length=100),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='username',
            field=models.CharField(default='tom1', max_length=70),
        ),
    ]
