# Generated by Django 4.1.7 on 2023-04-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_alter_logindetails_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='username',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='note',
            name='login_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.logindetails'),
        ),
    ]
