# Generated by Django 4.1.7 on 2023-04-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_alter_logindetails_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='login_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notes.logindetails'),
        ),
    ]
