# Generated by Django 4.1.7 on 2023-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_remove_note_login_details_delete_logindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='login_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
