# Generated by Django 4.1.7 on 2023-04-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_note_login_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='login_details',
        ),
    ]
